In [1]:
# get the numpy arange docstring
import numpy as np

In [2]:
import pandas as pd

In [3]:
%load_ext version_information

In [4]:
%version_information requests, numpy, pandas, matplotlib, seaborn, sklearn

Software versions
Python 3.6.2 32bit [MSC v.1900 32 bit (Intel)]
IPython 6.5.0
OS Windows 10 10.0.16299 SP0
requests 2.19.1
numpy 1.14.5
pandas 0.23.1
matplotlib 2.2.2
seaborn 0.9.0
sklearn 0.19.1
Tue Mar 19 19:09:50 2019 India Standard Time

In [5]:
%version_information requests, numpy, scipy, scikit-learn, matplotlib, pandas, pillow, graphviz, selenium, beautifulsoup4, seaborn, bokeh, ipython, version_information, ipython-sql, pdir2, graphviz

Software versions
Python 3.6.2 32bit [MSC v.1900 32 bit (Intel)]
IPython 6.5.0
OS Windows 10 10.0.16299 SP0
requests 2.19.1
numpy 1.14.5
scipy 1.1.0
scikit-learn 0.19.1
matplotlib 2.2.2
pandas 0.23.1
pillow 5.2.0
graphviz 0.8.4
selenium 3.13.0
beautifulsoup4 4.6.0
seaborn 0.9.0
bokeh 0.13.0
ipython 6.5.0
version_information 1.0.3
ipython-sql 0.3.9
pdir2 0.3.0
graphviz 0.8.4
Tue Mar 19 19:09:51 2019 India Standard Time

In [6]:
# Common standard libraries

import datetime
import time
import os

In [7]:
# Common external libraries

import pandas as pd
import numpy as np
import sklearn # scikit-learn
import requests
from bs4 import BeautifulSoup

In [8]:
# Visualization libraries

%matplotlib inline
import matplotlib.pyplot as plt
import seaborn as sns

In [9]:
from sklearn import datasets

In [10]:
boston = datasets.load_boston()

In [11]:
type(boston)

sklearn.utils.Bunch

In [12]:
print (boston.DESCR) #output omitted due to length

Boston House Prices dataset

Notes
------
Data Set Characteristics:  

    :Number of Instances: 506 

    :Number of Attributes: 13 numeric/categorical predictive
    
    :Median Value (attribute 14) is usually the target

    :Attribute Information (in order):
        - CRIM     per capita crime rate by town
        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.
        - INDUS    proportion of non-retail business acres per town
        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)
        - NOX      nitric oxides concentration (parts per 10 million)
        - RM       average number of rooms per dwelling
        - AGE      proportion of owner-occupied units built prior to 1940
        - DIS      weighted distances to five Boston employment centres
        - RAD      index of accessibility to radial highways
        - TAX      full-value property-tax rate per $10,000
        - PTRATIO  pupil-teacher ratio by town
      

In [13]:
X, y = boston.data, boston.target

In [14]:
from sklearn import preprocessing

In [15]:
X[:, :3].mean(axis=0) # mean of first 3 feature

array([ 3.59376071, 11.36363636, 11.13677866])

In [16]:
X[:, :3].std(axis=0)

array([ 8.58828355, 23.29939569,  6.85357058])

In [17]:
X_2 = preprocessing.scale(X[:, :3])

In [18]:
X_2.mean(axis=0)

array([ 6.34099712e-17, -6.34319123e-16, -2.68291099e-15])

In [19]:
X_2.std(axis=0)

array([1., 1., 1.])