In [21]:
import numpy as np

Produce a NumPy array of 10 digits

In [22]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

The array looks like a Python list with only one pair of brackets. This means it is of one dimension. Store the array and find out the shape:


In [23]:
array_1 = np.arange(10)
array_1.shape

(10,)

Find number of dimensions of array_1

In [24]:
array_1.ndim

1

The array has 10 elements. Reshape the array by calling the reshape method:

In [25]:
array_1.reshape((5,2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [26]:
array_1 = array_1.reshape((5,2))

In [27]:
array_1.ndim

2

The array has 10 elements. Reshape the array by calling the reshape method:

In [28]:
array_1 + 1

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

multiply the array by itself

In [29]:
array_2 = np.arange(10)
array_2 * array_2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

this is equivalent to array_2 * array_2

In [32]:
array_2 = array_2 ** 2
array_2

array([[   0,    1],
       [  16,   81],
       [ 256,  625],
       [1296, 2401],
       [4096, 6561]])

In [33]:
array_2 = array_2.reshape((5,2))
array_2


array([[   0,    1],
       [  16,   81],
       [ 256,  625],
       [1296, 2401],
       [4096, 6561]])