In [37]:
import numpy as np

Produce a NumPy array of 10 digits

In [38]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

The array looks like a Python list with only one pair of brackets. This means it is of one dimension. Store the array and find out the shape:


In [39]:
array_1 = np.arange(10)
array_1.shape

(10,)

Find number of dimensions of array_1

In [40]:
array_1.ndim

1

The array has 10 elements. Reshape the array by calling the reshape method:

In [41]:
array_1.reshape((5,2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [42]:
array_1 = array_1.reshape((5,2))

In [43]:
array_1.ndim

2

The array has 10 elements. Reshape the array by calling the reshape method:

In [44]:
array_1 + 1

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

multiply the array by itself

In [45]:
array_2 = np.arange(10)
array_2 * array_2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

this is equivalent to array_2 * array_2

In [46]:
array_2 = array_2 ** 2
array_2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [47]:
array_2 = array_2.reshape((5,2))
array_2


array([[ 0,  1],
       [ 4,  9],
       [16, 25],
       [36, 49],
       [64, 81]])

In [48]:
array_1 = array_1 + 1
array_1

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [49]:
array_1 + array_2

array([[ 1,  3],
       [ 7, 13],
       [21, 31],
       [43, 57],
       [73, 91]])

Initialize an array of zeros with np.zeros.

In [50]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

Initialize an array of ones using np.ones. Introduce a dtype argument, set to np.int, to ensure that the ones are of NumPy integer type

In [52]:
np.ones((5,2), dtype=np.int32)

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

Use np.empty to allocate memory for an array of a specific size and dtype, but no particular initialized values:

In [54]:
np.empty((5,2), dtype=np.float64)

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

Look up the values of the two-dimensional arrays with indexing:

In [55]:
array_1[0,0]

1

View the first row:

In [56]:
array_1[0, :]

array([1, 2])

view the first column:

In [57]:
array_1[:, 0]

array([1, 3, 5, 7, 9])

View specific values along both axes

In [58]:
array_1[2:5, :]

array([[ 5,  6],
       [ 7,  8],
       [ 9, 10]])

View the second to the fourth rows only along the first column

In [59]:
array_1[2:5,0]

array([5, 7, 9])

produce a Boolean array:

In [60]:
array_1 > 5

array([[False, False],
       [False, False],
       [False,  True],
       [ True,  True],
       [ True,  True]])

Place brackets around the Boolean array to filter by the Boolean array:

In [61]:
array_1[array_1>5]

array([ 6,  7,  8,  9, 10])

In [62]:
array_1

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

Add all the elements of the array with the sum method.

In [63]:
array_1.sum()

55

Find all the sums by row:

In [65]:
array_1.sum(axis=1)

array([ 3,  7, 11, 15, 19])

Find all the sums by column:

In [66]:
array_1.sum(axis=0)

array([25, 30])

mean of each column

In [67]:
array_1.mean(axis=0)

array([5., 6.])

In [68]:
array_3 = np.array([np.nan, 0, 1, 2, np.nan])

 NaN values with a special Boolean array created by the np.isnan function:

In [69]:
np.isnan(array_3)

array([ True, False, False, False,  True])

Filter the NaN values by negating the Boolean array with the symbol ~ and placing brackets around the expression:

In [71]:
array_3[~np.isnan(array_3)]

array([0., 1., 2.])

set the NaN values to zero:

In [72]:
array_3[np.isnan(array_3)] = 0
array_3

array([0., 0., 1., 2., 0.])